Repository rswag/rswag, pull requests merged in 2023-11, with the labels that each got.

#625 upgrade to ruby 3.0.6 and rails 7.0.4.3 in local dev
  .github/workflows/ruby.yml
  .ruby-version
  Dockerfile
  Gemfile
  rswag-specs/lib/rswag/specs/example_group_helpers.rb
  rswag-specs/lib/rswag/specs/example_helpers.rb
  rswag-specs/lib/rswag/specs/openapi_formatter.rb
Labels: dependencies

#695 docs: Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#688 Add warning about methods renaming
  CHANGELOG.md
  rswag-specs/lib/rswag/specs/configuration.rb
  rswag-ui/lib/rswag/ui/configuration.rb
Labels: breaking-change, documentation

#702 Fix deprecation warnings in version 2.12.0
  CHANGELOG.md
  Gemfile
  README.md
  rswag-api/lib/generators/rswag/api/install/templates/rswag_api.rb
  rswag-api/lib/rswag/api.rb
  rswag-api/lib/rswag/api/configuration.rb
  rswag-api/lib/rswag/api/middleware.rb
  rswag-api/rswag-api.gemspec
  rswag-api/spec/lib/rswag/api/configuration_spec.rb
  rswag-api/spec/lib/rswag/api_spec.rb
  rswag-api/spec/rswag/api/middleware_spec.rb
  rswag-api/spec/spec_helper.rb
  rswag-specs/lib/generators/rswag/specs/install/templates/swagger_helper.rb
  rswag-specs/lib/rswag/specs.rb
  rswag-specs/lib/rswag/specs/configuration.rb
  rswag-specs/lib/rswag/specs/example_group_helpers.rb
  rswag-specs/lib/rswag/specs/railtie.rb
  rswag-specs/lib/rswag/specs/request_factory.rb
  rswag-specs/lib/rswag/specs/response_validator.rb
  rswag-specs/lib/rswag/specs/swagger_formatter.rb
  rswag-specs/lib/tasks/rswag-specs_tasks.rake
  rswag-specs/spec/rswag/specs/configuration_spec.rb
  rswag-specs/spec/rswag/specs/example_helpers_spec.rb
  rswag-specs/spec/rswag/specs/request_factory_spec.rb
  rswag-specs/spec/rswag/specs/response_validator_spec.rb
  rswag-specs/spec/rswag/specs/swagger_formatter_spec.rb
  rswag-specs/spec/rswag/specs_spec.rb
  rswag-ui/lib/generators/rswag/ui/install/templates/rswag_ui.rb
  rswag-ui/lib/rswag/ui.rb
  rswag-ui/lib/rswag/ui/configuration.rb
  test-app/config/initializers/rswag-api.rb
  test-app/config/initializers/rswag-ui.rb
  test-app/db/schema.rb
  test-app/spec/integration/auth_tests_spec.rb
  test-app/spec/integration/blogs_spec.rb
  test-app/spec/integration/openapi3_spec.rb
  test-app/spec/rake/rswag_specs_swaggerize_spec.rb
  test-app/spec/swagger_helper.rb
  test-app/swagger/v1/swagger.json
  test-app/swagger/v3/openapi.json
Labels: bug, documentation

#698 chore: add more information about generating docs
  CHANGELOG.md
  README.md
Labels: documentation
