Repository rswag/rswag, pull requests merged in 2023-12, with the labels that each got.

#639 Add support for text/plain body format
  CHANGELOG.md
  rswag-specs/lib/rswag/specs/request_factory.rb
  rswag-specs/spec/rswag/specs/request_factory_spec.rb
Labels: enhancement

#707 CI: Tell dependabot to update GH Actions
  .github/dependabot.yml
  CHANGELOG.md
Labels: dependencies

#715 Fix broken JSON-schema page link
  CHANGELOG.md
  README.md
Labels: bug, documentation
